/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface':                    '#faf8ff',
        'surface-dim':                '#d9d9e5',
        'surface-bright':             '#faf8ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f3f3fe',
        'surface-container':          '#ededf9',
        'surface-container-high':     '#e7e7f3',
        'surface-container-highest':  '#e1e2ed',
        'on-surface':                 '#191b23',
        'on-surface-variant':         '#434655',
        'inverse-surface':            '#2e3039',
        'inverse-on-surface':         '#f0f0fb',
        'outline':                    '#737686',
        'outline-variant':            '#c3c6d7',
        'surface-tint':               '#0053db',
        'primary':                    '#004ac6',
        'on-primary':                 '#ffffff',
        'primary-container':          '#2563eb',
        'on-primary-container':       '#eeefff',
        'inverse-primary':            '#b4c5ff',
        'secondary':                  '#006e2f',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#6bff8f',
        'on-secondary-container':     '#007432',
        'tertiary':                   '#943700',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#bc4800',
        'on-tertiary-container':      '#ffede6',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'primary-fixed':              '#dbe1ff',
        'primary-fixed-dim':          '#b4c5ff',
        'on-primary-fixed':           '#00174b',
        'on-primary-fixed-variant':   '#003ea8',
        'secondary-fixed':            '#6bff8f',
        'secondary-fixed-dim':        '#4ae176',
        'on-secondary-fixed':         '#002109',
        'on-secondary-fixed-variant': '#005321',
        'tertiary-fixed':             '#ffdbcd',
        'tertiary-fixed-dim':         '#ffb596',
        'on-tertiary-fixed':          '#360f00',
        'on-tertiary-fixed-variant':  '#7d2d00',
        'background':                 '#faf8ff',
        'on-background':              '#191b23',
        'surface-variant':            '#e1e2ed',
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono:  ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg':     ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md':    ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg':        ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':        ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-mono':     ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      maxWidth: {
        container: '1120px',
      },
      spacing: {
        gutter: '24px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
